### ISSUE TITLE
Will you add the "Modify Data" function?

### ISSUE THREAD

**Issue by Virace** [CommunityDragon/CDTB#14]
Will you add the "Modify Data" function?

**Comment by benoitryder** [comment]
What do you mean? What is this "Modify Data" function?

**Comment by Virace** [comment]
> What do you mean? What is this "Modify Data" function?

for example, replace one of the files in WAD files.

**Comment by benoitryder** [comment]
No. There is no plans for methods to create or modify WAD files.

**Comment by Virace** [comment]
> No. There is no plans for methods to create or modify WAD files.

ok,thanks
