### ISSUE TITLE
Some pictures have weird "transparent pixels"

### ISSUE THREAD

**Issue by trebonius0** [CommunityDragon/CDTB#17]
I just noticed that some pictures do have weird transparent pixels.
http://raw.communitydragon.org/9.12/plugins/rcp-be-lol-game-data/global/default/data/items/icons2d/3158_ionian_boots_of_lucidity.png for instance

(on chrome the issue does not appear for some reason, but some pixels are white on FF or if you download the picture on Windows and open it)

![image](https://user-images.githubusercontent.com/14201457/59451998-13d5ab80-8e0d-11e9-8a4f-ff0dcc9cbc15.png)

**Comment by Morilli** [comment]
If these pixels are actually transparent, their color appears to be that of the background, which is usually black in chrome, but can be any, like white.

**Comment by benoitryder** [comment]
I confirm: the pixels are transparent in the PNG file (Windows handle them correctly by the way).
We get the PNG as-is from Riot's files (no transformations). And the DDS file from game client files has the same transparent pixels.

**Comment by Querijn** [comment]
Might be good to transform it. Is it consistent for all or just this item?

**Comment by benoitryder** [comment]
CDragon's raw provides files as-is, with no changes. We transform some files to more usable formats but that's all.

[This old item](https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/data/items/icons2d/3178_ionicspark.png) has the same issue, but I think it's the only other one. And a lot of items use transparency for cut corners.
