### ISSUE TITLE
"Parser Error" when trying to download data 

### ISSUE THREAD

**Issue by trebonius0** [CommunityDragon/CDTB#2]
Hey guys

I've been trying to use your tool to download data. 
I'm running on Ubuntu 16.04 64bits and have installed all the required dependencies, and all my packages are up to date. I'm using python 3.5.2

When launching  `python3 -m cdragontoolbox download patch=` or `python3 -m cdragontoolbox -h` I get the following error

> Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 144, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jn/Git/CDTB/cdragontoolbox/__main__.py", line 31
    parser.error(f"invalid component: {component}")
                                                 ^
SyntaxError: invalid syntax

Can you fix this ?

Thanks !

**Comment by jjmaldonis** [comment]
Hey this script requires python 3.6 for the f-string format we're using here. My guess is that Ubuntu comes with 3.4 or 3.5 installed instead.

Maybe we can downgrade this script to only require 3.5 but I'm not sure if there are other dependencies or not.

**Comment by costpermille** [comment]
python3 defaults to 3.5 on xenial and zesty, and 3.6 on artful and bionic. you're on xenial.

I usually use pyenv to run 3.7/6 on LTS ubuntu 16. I wouldn't want to downgrade from latest stable features, but that's my 2c.

**Comment by stelar7** [comment]
Not really an issue as the OP has the wrong python version. Should prolly add a version check?
