### ISSUE TITLE
is there files record the hero's lines by words

### ISSUE THREAD

**Issue by 1997Gongquan** [CommunityDragon/CDTB#26]
you know ,after getting the hero`s lines from 'Champions' folder. I hava to cost several hours to rename those lines one by one even through it`s  belong to a single hero.
so ,is there scipts record those lines in words.i don`t want to convert audio files to text any more....
thacks a lot.

**Comment by benoitryder** [comment]
If you seek for a text version of champion voice lines, AFAIK it does not exist.

**Comment by 1997Gongquan** [comment]
> If you seek for a text version of champion voice lines, AFAIK it does not exist.

that`s a terrible news.there are 38000 lines wait for me to rename them......
