### ISSUE TITLE
wad-extract, I got a wrong file.

### ISSUE THREAD

**Issue by Virace** [CommunityDragon/CDTB#30]
9.23
"c:\Riot Games\PBE\Game\DATA\FINAL\Localized\Global.en_US.wad.client"
data\menu\fontconfig_en_us.txt
like this
![pick](https://user-images.githubusercontent.com/19266538/69543339-57416200-0fc8-11ea-9aaa-4516e8e036c3.png)

**Comment by Morilli** [comment]
This is correct. Riot changed the format of these .txt files.

**Comment by benoitryder** [comment]
You can use `cdragontoolbox.rstfile.RstFile` to parse the new format into a map of translated strings, indexed by a hash of the symbolic name that was used in the previous text format.

**Comment by Virace** [comment]
Yes, it has been solved. Thank you.
